# Generated by Django 5.2.6 on 2025-09-08 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_productos_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='body',
            new_name='descripcion',
        ),
        migrations.AddField(
            model_name='producto',
            name='link_imagen',
            field=models.CharField(default='a', max_length=512),
            preserve_default=False,
        ),
    ]
