# Generated by Django 5.2.6 on 2025-09-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='link_imagen',
            field=models.URLField(),
        ),
    ]
